<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmJtgKM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmJtgKM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGmJtgKM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGmJtgKM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGmJtgKM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GmJtgKM',
    'container.build_id' => '1c3cc831',
    'container.build_time' => 1650200106,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmJtgKM');
