<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3J70jug\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3J70jug/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3J70jug.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3J70jug\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3J70jug\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3J70jug',
    'container.build_id' => '8942951e',
    'container.build_time' => 1650195676,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3J70jug');
