<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6ftYFZl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6ftYFZl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6ftYFZl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6ftYFZl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6ftYFZl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6ftYFZl',
    'container.build_id' => '3c9b88d4',
    'container.build_time' => 1650007440,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6ftYFZl');
